### ISSUE TITLE
Train/Dev/Test split problem

### ISSUE THREAD

**Issue by xixy** [thunlp/HMEAE#2]
For ACE 2005, you use a random split (529/30/40 documents) for train/dev/test data. 

We all use the same split following previous works, refer to https://github.com/lx865712528/EMNLP2018-JMEE/tree/master/qi_filelist

The split issue may lead to un-reliable performance.

**Comment by xixy** [comment]
怎么回事大兄弟，大家都这样split的吗？

        nw = self.source_files['nw']
        random.shuffle(nw)
        random.shuffle(nw)
        other_files = [file for dir in self.dirs for file in self.source_files[dir] if dir!='nw']+nw[40:]
        random.shuffle(other_files)
        random.shuffle(other_files)

        test_files = nw[:40]
        dev_files = other_files[:30]
        train_files = other_files[30:]

**Comment by wzq016** [comment]
Thank you for your interest to our paper!

In the experiment, we find that many papers(see following) only mention the split number and didn't mention the specific files. 

https://www.aclweb.org/anthology/P10-1081.pdf 
https://www.aclweb.org/anthology/P15-1017.pdf
https://www.aclweb.org/anthology/P13-1008.pdf

So in our experiment, we use random to get train/dev/test. Then we run this split on baseline model and see if baseline model can get the same score as original paper. If the score is too high or too low, we will random the split again until baseline model is stable. For example, at the beginning, we think we need to prevent data leaky, so we use the newest news as test set, however, we find that if we use this split, the baseline model's score is extremely high, which means that baseline model didn't use such split and we need to select other split. The split that will make baseline model stable is the split we finally used.

We didn't follow JMEE's split because the JMEE code has some problems, see issue 6: https://github.com/lx865712528/EMNLP2018-JMEE/issues/6. Also, we don't think every one use the split provided by JMEE.

Hope this can help.

**Comment by xixy** [comment]
In this way, we might have plenty of available splits. How can you traversal all the splits? It's impossible.

It would be a joke if we are competing for state-of-the-art performance but using different splits.

**Comment by wzq016** [comment]
First, I didn't say I **traversal all the splits**, what I was doing is that I tried **many** splits and find **a** split that can make baseline model have **almost same** score as original paper, so we can guarantee the split is relative reliable.

Second, about the split issue. Actually, for previous methods like JRNN, DMCNN, etc, the truth is that the split they used has a high probability that might be different from each other, since no paper gives a specific split. So what we can do is that we select the most reliable split from many possible splits and run the experiment. We also feel  helpless with the data set and split in this field, and that's the reason we are working on constructing a new dataset.

Third, it is not responsible to follow JMEE's split since its codes posted on GitHub have such serious problems, on the contrary, it is actually responsible not to follow JMEE's split. Besides, could you provide any evidence that support you assertion "we all used split given by JMEE"?

**Comment by Bakser** [comment]
Just a kind reminder. Please be polite in discussion. It is worthless to continue the discussion in aggressive words (no matter in English or Chinese) and claims without evidence. If you continue to do that,  we will have to label this issue as SPAM.

**Comment by xixy** [comment]
Thanks for answers.  I'm sorry for the aggressive words.

**Comment by wzq016** [comment]
It doesn't matter :), I will close this issue if you don't have other questions.

**Comment by xixy** [comment]
I still got another question

**Comment by xixy** [comment]
In test stage, your task is to classify each token into an specific event type or O-type. However, your data processing allows you to know the trigger span in test data (even though we don't know the exact type). Considering there existing multi-token triggers, don't you think it's a little far from reality? Normally, in test stage, you should not know the trigger span and treat each token as possible trigger candidate. I hope you got my point.

**Comment by wzq016** [comment]
For your first concern that trigger words indeed may have multi-tokens, indeed, in data-processing stage, I notice that there may have trigger words like "wrapped off". And in such case, we just treat "wrapped" as trigger word and ignore "wrapped off" this phrase. The reason is that, if we consider such condition, the complexity of the algorithm will be very high, for example, in ED stage,  if you have a sentence of n words, then you need to detect n times for 1 token trigger, n-1 times for 2 token trigger, ..., so the complexity will rise from O(n) to O(n^2), on the other side, the number of multi-token triggers in ACE05 is too small, so our treatment would not affect results, since our paper focus on EAE stage, we adapt this treatment.

For your second concern, EE actually has two stages. First is ED stage, in this stage, we detect trigger words and classify the event type. Second is EAE stage, we use the trigger words and event type predicted by ED stage (so may not be correct) to do argument extraction. The case you mention is not the pipeline what EE did. You can refer to the first paragraph of our paper for details of how EE pipeline works.
