### ISSUE TITLE
Could you release HMEAE(BERT) model ?

### ISSUE THREAD

**Issue by xixy** [thunlp/HMEAE#7]
Thank you very much for releasing the source code.

I noticed that code of DMCNN and HMEAE(DMCNN) is released while DMBERT and HMEAE(BERT) are missing. Can you release code for the two models?

Thank you.

**Comment by rz-zhang** [comment]
Thank you for the released code.
I am also interested in the HMEAE(BERT) model. It will be great if you are willing to open the source code.
Many thanks!

**Comment by Bakser** [comment]
Thanks for your interest. The original implementations are out of date and cannot directly run since it uses some ancient libraries.
We will reimplement and release it after recovering it from the failed servers. But it may take some time. If you are interested in using recent BERT implementations for EE, maybe you can refer to [that repo](https://github.com/Bakser/DMBERT) for some information.
