### ISSUE TITLE
Question about TAC KBP

### ISSUE THREAD

**Issue by xixy** [thunlp/HMEAE#9]
Thank you for releasing the code for HMEAE.

My question about TAC KBP 2016 dataset is:

1. Did you use ACE train, ACE dev and TAC-KBP 2016 as train/dev/test data in the experiment ?
2. Could you release the preprocess code for TAC-KBP 2016? Or the generated json file will be greatly helpful

Thank you and looking forward to your reply.

**Comment by xixy** [comment]
Besides, I searched 'LDC2017E05' and didn't find that data. The most close dataset is : https://catalog.ldc.upenn.edu/LDC2020T03

Would you kindly give me the right URL for the data? Thank you.

**Comment by xixy** [comment]
Besides, I searched 'LDC2017E05' and didn't find that data. The most close dataset is : https://catalog.ldc.upenn.edu/LDC2020T03

Would you kindly give me the right URL for the data? Thank you.

**Comment by xixy** [comment]
Besides, I searched 'LDC2017E05' and didn't find that data. The most close dataset is : https://catalog.ldc.upenn.edu/LDC2020T03

Would you kindly give me the right URL for the data? Thank you.

**Comment by xixy** [comment]
Besides, I searched 'LDC2017E05' and didn't find that data. The most close dataset is : https://catalog.ldc.upenn.edu/LDC2020T03

Would you kindly give me the right URL for the data? Thank you.

**Comment by Bakser** [comment]
Thanks for your interest in our work!
1. Yes.
2. The data and identifier of LDC2017E05 were provided by TAC KBP 2017. It seems that the dataset hasn't been made public by LDC. And we are sorry that due to the [license](https://tac.nist.gov/2017/KBP/TACKBP17_Eval_License.pdf) limitation, we cannot redistribute this dataset. Hopefully, it will be released by LDC soon as the 2014 and 2015 datasets have been released (LDC2020T03 as you referred). We will find time to clean the preprocessing codes and release them recently. Thanks for the question.
